openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Pilotes management application"
paths:
  /pilotes-manager/customer:
    post:
      tags:
        - Private
      summary: "Insert a new customer"
      operationId: "insertCustomer"
      requestBody:
        description: Customer request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsertCustomerRequest'
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: "Data not found"
        '500':
          description: "Internal error"
  /pilotes-manager/order/{customerTelephone}/pilotes/{numberOfPilotes}:
    post:
      tags:
        - Private
      summary: "Insert a new pilotes order by customer telephone"
      operationId: "insertPilotesOrder"
      parameters:
        - name: customerTelephone
          description: customer telephone
          in: path
          required: true
          schema:
            type: string
        - name: numberOfPilotes
          description: number of pilotes
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PilotesOrder'
        '404':
          description: "Data not found"
        '500':
          description: "Internal error"
  /pilotes-manager/orders/pilotes:
    get:
      tags:
        - Private
      summary: "Get all orders"
      operationId: "getAllPilotesOrders"
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PilotesOrder'
        '404':
          description: "Data not found"
        '500':
          description: "Internal error"
  /pilotes-manager/order/pilotes/{orderNumber}:
    patch:
      tags:
        - Private
      summary: "Modify order"
      operationId: "modifyPilotesOrder"
      requestBody:
        description: Modify order request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/ModifyOrderRequest'
      parameters:
        - name: orderNumber
          description: order number
          in: path
          required: true
          schema:
            type: number
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PilotesOrder'
        '404':
          description: "Data not found"
        '500':
          description: "Internal error"
  /pilotes-manager/orders/pilotes/{customerPartialName}:
    get:
      tags:
        - Private
      summary: "Get all orders by partial name"
      operationId: "getAllPilotesOrdersByName"
      parameters:
        - name: customerPartialName
          description: customer partial name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PilotesOrder'
        '404':
          description: "Data not found"
        '500':
          description: "Internal error"


components:
  schemas:
    InsertCustomerRequest:
      type: object
      required:
        - name
        - surname
        - telephoneNumber
        - pilotesOrder
      properties:
        name:
          type: string
        surname:
          type: string
        telephoneNumber:
          type: string
        pilotesOrders:
          type: array
          items:
            $ref: '#/components/schemas/PilotesOrder'

    Customer:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        telephoneNumber:
          type: string
        pilotesOrders:
          type: array
          items:
            $ref: '#/components/schemas/PilotesOrder'
    PilotesOrder:
      type: object
      properties:
        orderNumber:
          type: number
        deliveryAddress:
          type: string
        pilotesNumber:
          type: integer
        totalOrderAmount:
          type: number
        createdAt:
          type: "string"
          format: "date-time"
    ModifyOrderRequest:
      type: object
      properties:
        orderNumber:
          type: number
        deliveryAddress:
          type: string
        pilotesNumber:
          type: integer
